subscription_id      = "faXXXXXXXXXXXXXXXXXXX"
resource_group_name  = "example1-resources"
location             = "Centarl India"
registry_name        = "acrjail001"
webhook_name         = "webhookjail001"
